### ISSUE TITLE
Contributing the file describing how to work with me

### ISSUE THREAD

**Issue by aramaniuk** [aramaniuk/githubtraining#2]
Currently repository doesn't have good instructions about how a collaborator can contribute to the project
## TODO
- [x] `CONTRIBUTING.mg` created 
- [x] Explaing Fork and Pull Request
- [x] Link to it from `README.md`
